In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
url = "https://www.starbucks.co.kr/store/getStore.do?r=RO98U559C0"

# 시,도 분류코드를 star_list로 담고
star_list = ['01','02','03','04','05','06','07','08','09',
             '10','11','12','13','14','15','16','17']
# 01 서울, 02 광주, 03 대구, 04 대전, 05 부산, 06 울산, 07 인천, 08 경기, 09 강원,
# 10 경남, 11 경북, 12 전남, 13 전북, 14 충남, 15 충북, 16 제주, 17 세종
# 각 시도의 데이터를 json타입으로 데이터를 받을 star_json 리스트 생성.
star_json = []

# 각 시도 순서대로 request하여 json타입의 데이터를 star_json에 넣는다
for i in star_list:
    response = requests.post(url,data={
    'p_sido_cd' : i,                    # 시,도 분류 코드
    'p_gugun_cd': '',                   # 시,군,구 분류 코드
    'in_biz_cd' : '' ,                  # 알 수 없는 정보
    'iend'      : 2000,                 # 불러올 최대 매장 수
    'set_date'  : ''                    # 알 수 없는 정보
    })
    star_json.append(response.json())

In [3]:
# 각 시도별 json타입으로 만든 데이터를 순차적으로 데이터프레임으로 만들고
# concat으로 생성 즉시 붙여서 df 변수에 넣는다
df = pd.concat(pd.DataFrame(star_json[i]['list']) for i in range(17))

In [4]:
# df 확인
pd.set_option('display.max_columns', None)
print(df.shape)
df.head()

(1623, 129)

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,address,new_img_nm,p_pro_seq,p_view_yn,p_sido_cd,p_gugun_cd,p_store_nm,p_theme_cd,p_wireless_yn,p_smoking_yn,p_book_yn,p_music_yn,p_terrace_yn,p_table_yn,p_takeout_yn,p_parking_yn,p_dollar_assent,p_card_recharge,p_subway_yn,stb_store_file_renew,stb_store_theme_renew,stb_store_time_renew,stb_store_lsm,s_code,s_name,tel,fax,sido_code,sido_name,gugun_code,gugun_name,addr,park_info,new_state,theme_state,new_bool,search_text,ins_lat,ins_lng,in_distance,out_distance,all_search_cnt,addr_search_cnt,store_search_cnt,rowCount,store_nm,store_cd,s_biz_code,new_icon,set_user,favorites,map_desc,notice,defaultimage,etcimage,in_biz_cd,in_store_cd,in_favorites,in_user_id,in_biz_cds,in_biz_arr,in_biz_arrdata,in_scodes,in_scode_arr,in_scode_arrdata,disp,set_date,hlytag,hlytag_msg,vSal,istart,iend,open_dt,gold_card,ip_lat,ip_long,espresso,new_store,premiere_food,doro_address,cold_blew,my_siren_order_store_yn,whcroad_yn,skuNo,skuName,skuImgUrl,stock_count,store_area_name,store_area_code,is_open,gift_stock_yn,lat,lot,t20,t04,t03,t01,t12,t09,t06,t10,p10,p50,p20,p60,p30,p70,p40,p80,t22,t21,p90,t05,t30,t36,t27,t29,t43,t48
0,0,None,None,None,None,None,None,None,None,None,None,None,0,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1509,역삼아레나빌딩,1522-3232,02-568-3763,01,서울,0101,강남구,서울특별시 강남구 역삼동 721-13 아레나빌딩,None,None,T05@T08@T16@T17@T20@T21@T30@T36@T52@P80@P90,0,,,,0,None,-1,-1,-1,30,,0,3762,N,,0,None,None,/upload/store/2020/09/[3762]_20200917031519_6j...,None,None,None,None,None,0,None,None,0,None,None,None,None,None,None,,1,60,20190613,0,,,,,,서울특별시 강남구 언주로 425 (역삼동),,N,WHCROAD,,,,0,None,A01,None,None,37.501087,127.043069,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,None,None,None,None,None,None,None,None,None,None,None,0,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1434,논현역사거리,1522-3232,02-3442-3673,01,서울,0101,강남구,서울특별시 강남구 논현동 142-2 정일빌딩,None,None,T05@T08@T16@T17@T20@T21@T30@T52@P70@P80@P90,0,,,,0,None,-1,-1,-1,30,,0,3672,N,,0,None,None,/upload/store/2018/12/[3672]_20181211120009_t9...,None,None,None,None,None,0,None,None,0,None,None,None,None,None,None,,1,60,20181123,0,,,,,,서울특별시 강남구 강남대로 538 (논현동),,N,,,,,0,None,A01,None,None,37.510178,127.022223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,None,None,None,None,None,None,None,None,None,None,None,0,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1595,신사역성일빌딩,1522-3232,02-547-3859,01,서울,0101,강남구,서울특별시 강남구 논현동 18-4 성일빌딩,None,None,T05@T08@T16@T17@T20@T21@T30@T34@T52@P70@P80,0,,,,0,None,-1,-1,-1,30,,0,3858,N,,0,None,None,/upload/store/2019/12/[3858]_20191218124337_c8...,None,None,None,None,None,0,None,None,0,None,None,None,None,None,None,,1,60,20191219,0,,,,,,서울특별시 강남구 강남대로 584 (논현동),,N,,,,,0,None,A01,None,None,37.514132,127.020563,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,None,None,None,None,None,None,None,None,None,None,None,0,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1527,국기원사거리,1522-3232,02-568-3669,01,서울,0101,강남구,서울특별시 강남구 역삼동 648-22 동찬빌딩,None,None,T05@T08@T16@T17@T20@T21@T30@T32@T34@T36@T52@P7...,0,,,,0,None,-1,-1,-1,30,,0,3669,N,,0,None,None,/upload/store/2019/07/[3669]_20190730073527_5n...,None,None,None,None,None,0,None,None,0,None,None,None,None,None,None,,1,60,20190731,0,,,,,,서울특별시 강남구 테헤란로 125 (역삼동),,N,WHCROAD,,,,0,None,A01,None,None,37.499517,127.031495,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,None,None,None,None,None,None,None,None,None,None,None,0,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1468,스탈릿대치R,1522-3232,02-568-3705,01,서울,0101,강남구,서울특별시 강남구 대치동 599 대원빌딩,None,None,T03@T05@T08@T16@T17@T20@T21@T22@T26@T29@T30@T3...,0,,,,0,None,-1,-1,-1,30,,0,3703,N,,0,None,None,/upload/store/2019/02/[3703]_20190215093408_m3...,None,None,None,None,None,0,None,None,0,None,None,None,None,None,None,,1,60,20190214,0,,,,,,서울특별시 강남구 남부순환로 2947 (대치동),,N,WHCROAD,,,,0,None,A01,None,None,37.494668,127.062583,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
# 필요한 컬럼만 부르고, 한글명 컬럼으로 변환한다.
col = ['지점명', '시도', '시군구', '도로명주소', '위도', '경도']
star_df = df[['s_name', 'sido_name', 'gugun_name'
                       , 'doro_address', 'lat', 'lot']]
star_df.columns = col
# 인덱스 초기화
star_df.reset_index(drop=True, inplace=True)
star_df

,지점명,시도,시군구,도로명주소,위도,경도
0,역삼아레나빌딩,서울,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,서울,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,서울,강남구,서울특별시 강남구 강남대로 584 (논현동),37.514132,127.020563
3,국기원사거리,서울,강남구,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495
4,스탈릿대치R,서울,강남구,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583
...,...,...,...,...,...,...
1618,세종이마트,세종,None,세종특별자치시 금송로 687(가람동 406) 이마트 세종점,36.4712189,127.2509973
1619,세종청사,세종,None,세종특별자치시 도움8로 81 (어진동),36.504565,127.270769
1620,세종아름,세종,None,"세종특별자치시 아름서1길 13-9 (아름동) 103,104,105,202,203호",36.51188,127.24277
1621,세종소담,세종,None,"세종특별자치시 소담3로 8 (소담동) 1동 12호,13호,14호,15호,15a호,16호",36.485755,127.300509
1622,세종충남대학교병원,세종,None,세종특별자치시 보듬7로 20 (도담동) 헬스케어센터 1층,36.51936,127.25828

In [6]:
# 시도별 지점 수 확인
star_df['시도'].value_counts()

서울     568
경기     369
부산     128
대구      71
인천      64
경남      62
광주      59
대전      57
경북      47
충남      35
울산      29
전북      27
충북      25
제주      23
전남      23
강원      19
세종      11
강원도      6
Name: 시도, dtype: int64

In [7]:
# '강원도'로 표기된 데이터 '강원'으로 변경
star_df['시도'] = star_df['시도'].apply(lambda x : '강원' if x == '강원도' else x)
star_df['시도'].value_counts()

<ipython-input-7-b73f26ee7558>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  star_df['시도'] = star_df['시도'].apply(lambda x : '강원' if x == '강원도' else x)

서울    568
경기    369
부산    128
대구     71
인천     64
경남     62
광주     59
대전     57
경북     47
충남     35
울산     29
전북     27
강원     25
충북     25
제주     23
전남     23
세종     11
Name: 시도, dtype: int64

In [8]:
# 전국에 DT점 확인
star_df.loc[star_df['지점명'].str.contains('DT')]

,지점명,시도,시군구,도로명주소,위도,경도
97,방화DT,서울,강서구,서울특별시 강서구 방화대로 375 (방화동),37.574339,126.816415
101,화곡DT,서울,강서구,서울특별시 강서구 등촌로 57 (화곡동),37.535149,126.863232
117,신림DT,서울,관악구,서울특별시 관악구 남부순환로 1419 (신림동),37.480935,126.908407
119,낙성대DT,서울,관악구,서울특별시 관악구 남부순환로 1948 (봉천동),37.476169,126.965005
130,구의DT,서울,광진구,서울특별시 광진구 광나루로 519 (구의동),37.5451984,127.0871587
...,...,...,...,...,...,...
1605,제주애월DT,제주,제주시,제주특별자치도 제주시 애월읍 애월해안로 376,33.472780,126.348739
1608,제주용담DT,제주,제주시,제주특별자치도 제주시 서해안로 380 (용담삼동) 화이트하우스,33.512345,126.484564
1610,제주서해안로DT,제주,제주시,제주특별자치도 제주시 서해안로 624 (용담삼동),33.5167857,126.5035553
1611,제주일도DT,제주,제주시,제주특별자치도 제주시 동광로 130 (일도이동),33.5073284,126.5408980
1612,세종다정DT,세종,None,세종특별자치시 다정북로 219 (다정동),36.494878,127.255384

In [9]:
# 서울 강남구의 스타벅스 지점 수 확인
star_df[(star_df['시도'] == '서울') & (star_df['시군구'] == '강남구')]

,지점명,시도,시군구,도로명주소,위도,경도
0,역삼아레나빌딩,서울,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,서울,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,서울,강남구,서울특별시 강남구 강남대로 584 (논현동),37.514132,127.020563
3,국기원사거리,서울,강남구,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495
4,스탈릿대치R,서울,강남구,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583
...,...,...,...,...,...,...
82,강남세곡,서울,강남구,서울특별시 강남구 헌릉로569길 18 (세곡동),37.467274319644,127.099929726
83,대치삼성프라자,서울,강남구,서울특별시 강남구 영동대로 237 (대치동),37.500313,127.066961
84,테헤란로아남타워,서울,강남구,서울특별시 강남구 테헤란로 311 (역삼동),37.50383,127.04487
85,삼성동,서울,강남구,서울특별시 강남구 영동대로96길 12 (삼성동),37.510843366121534,127.06363342044263
86,역삼이마트,서울,강남구,서울특별시 강남구 역삼로 310 (역삼동),37.499367,127.048425